kind: ReplicationController
apiVersion: v1
metadata:
  name: ipython-controller
spec:
  replicas: 1
  selector:
    component: ipython-master
  template:
    metadata:
      labels:
        component: ipython-master
    spec:
      containers:
        - name: ipython-master
          image: maccam912/jupyter
          #command: ["/start-master"]
          ports:
            - containerPort: 8888 
          resources:
            requests:
              cpu: 100m
